global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
  - job_name: "airflow-statsd"
    metrics_path: /metrics
    static_configs:
      - targets: ["statsd-exporter:9102"]
